/**
 * blog-core-v2 한국어 기본 i18n 문자열
 *
 * 모든 BlogI18nStrings 키에 대한 기본값을 제공한다.
 * 컴포넌트는 resolveI18n(override)로 fallback이 채워진 완전한 객체를 받는다.
 *
 * 호스트가 별도의 언어를 사용할 때는 동일한 형식의 Partial<BlogI18nStrings>를
 * BlogConfig.i18n에 전달하면 된다.
 */
import type { BlogI18nStrings } from './types';

/** 한국어 기본 문자열 — 기존 v1 하드코딩 값과 하위 호환 유지 */
export const DEFAULT_I18N_KO: Required<BlogI18nStrings> = {
  // ── 관리자 UI: 목록 / 공통 ──
  adminListTitle: '블로그 관리',
  adminCreateButton: '+ 새 글 추가',
  adminCreateTitle: '글 작성',
  adminEditTitle: '글 편집',
  adminSaveButton: '저장',
  adminCancelButton: '취소',
  adminPublishedLabel: '공개',
  adminUnpublishedLabel: '비공개',
  adminFeaturedLabel: '홈 표시',
  adminDeleteConfirm: '삭제하시겠습니까?',
  adminBulkDeleteConfirm: '선택한 항목을 삭제하시겠습니까?',
  adminListEmpty: '표시할 글이 없습니다.',
  adminUnknownError: '알 수 없는 오류가 발생했습니다.',
  adminPublishedSuffix: '저장되었습니다.',
  adminDraftSuffix: '수정되었습니다.',
  adminSearchPlaceholder: '검색',
  adminSelectAll: '전체 선택',
  adminCategoryAll: '전체',
  adminCountSuffix: '건',
  adminBackButton: '돌아가기',

  // ── 관리자 UI: 정렬 ──
  adminSortCreatedAt: '등록일순',
  adminSortPublishedAt: '발행일순',
  adminSortUpdatedAt: '수정일순',

  // ── 관리자 UI: 뷰 / 탭 ──
  adminViewEdit: '편집',
  adminViewPreviewDetail: '상세 미리보기',
  adminViewPreviewList: '목록 미리보기',
  adminTabList: '목록',
  adminTabEditPreview: '편집 + 미리보기',
  adminTabDashboard: '대시보드',

  // ── 관리자 UI: 메타데이터 라벨 ──
  adminMetaPublishedAt: '발행',
  adminMetaCreatedAt: '등록',
  adminMetaUpdatedAt: '수정',
  adminViewCountLabel: '조회수',

  // ── 관리자 UI: 일괄 작업 ──
  adminBulkPublish: '공개',
  adminBulkUnpublish: '비공개',
  adminBulkFeature: '홈 표시',
  adminBulkUnfeature: '홈 해제',
  adminBulkDelete: '삭제',
  adminBulkClear: '선택 해제',
  adminBulkSelectedSuffix: '건 선택',

  // ── 관리자 폼: 라벨 & 플레이스홀더 ──
  adminTitleLabel: '제목',
  adminTitlePlaceholder: '제목을 입력하세요',
  adminTitleRequired: '제목을 입력해주세요',
  adminContentLabel: '본문',
  adminContentRequired: '본문을 입력해주세요',
  adminSlugLabel: '고유주소',
  adminSlugAutoGenerated: '고유주소-자동생성',
  adminSlugDuplicate: '✗ 중복',
  adminSlugInvalid: '✗ 형식오류',
  adminSlugAvailable: '✓ 사용 가능',
  adminSlugChecking: '확인 중...',
  adminCategoryLabel: '카테고리를 선택해주세요',
  adminExcerptLabel: '부제 / 요약 (선택)',
  adminExcerptPlaceholder: '부제 / 요약 (선택)',
  adminCoverImageLabel: '대표 이미지',
  adminAttachmentsLabel: '첨부파일',
  adminBlocksLabel: '콘텐츠 블록',
  adminCtaLabel: 'CTA 버튼',
  adminPublishedAtLabel: '발행일시',
  adminBasicInfoLabel: '기본 정보',
  adminRequiredLabel: '필수',
  adminOptionalLabel: '선택',
  adminFeaturedShort: '홈',
  adminItemNoTitle: '(없음)',
  adminSampleButton: '예시 콘텐츠',
  adminBlocksHint: '텍스트/이미지 자유 편집',
  adminBlocksTag: '텍스트/이미지 자유 편집',
  adminImageRatioHint: '16:9 비율 권장',
  adminContentPlaceholder: '본문을 입력하세요',
  adminSlugPlaceholder: '고유주소를 입력하세요',

  // ── 관리자 폼: 업로드 & 첨부 ──
  adminUploadFailed: '업로드 실패',
  adminUnsupportedFileType: '지원하지 않는 파일 형식입니다. (허용: jpeg, png, webp, gif)',
  adminFileUploadError: '업로드 중 오류 발생',
  adminImageOnlyAllowed: '이미지 파일만 업로드할 수 있습니다.',
  adminSaving: '저장 중...',
  adminLoading: '로딩 중...',
  adminUploading: '업로드 중...',
  adminImageResizing: '이미지 최적화 중...',
  adminDropHere: '여기에 놓으세요',
  adminImageUploadButton: '+ 이미지업로드',
  adminAttachmentTitle: '첨부파일',
  adminAttachmentAddButton: '+ 파일 추가',
  adminAttachmentMaxExceeded: '첨부파일 최대 개수를 초과했습니다.',
  adminAttachmentsHint: 'PDF, HWP 등 문서를 첨부할 수 있습니다.',

  // ── 관리자 폼: CTA ──
  adminCtaDescription: '기사 끝에 표시되는 안내 버튼입니다.',
  adminCtaToggle: 'CTA 버튼 표시',
  adminCtaMessageLabel: '안내 문구',
  adminCtaMessagePlaceholder: '안내 메시지를 입력하세요',
  adminCtaButtonLabel: '버튼 텍스트',
  adminCtaButtonPlaceholder: '버튼 텍스트',
  adminCtaUrlLabel: '링크 URL',

  // ── 관리자 대시보드 ──
  dashboardTitle: '대시보드',
  dashboardTotal: '전체 글',
  dashboardPublished: '공개 글',
  dashboardUnpublished: '비공개 글',
  dashboardFeatured: '추천 글',
  dashboardByCategory: '카테고리별 글 수',
  dashboardRecentPosts: '최근 작성된 글',
  dashboardNoData: '데이터가 없습니다.',

  // ── 공개 UI ──
  publicAllCategory: '전체',
  publicPrevPage: '이전',
  publicNextPage: '다음',
  publicBackToList: '목록으로',
  publicAttachmentsLabel: '첨부파일',
  publicPrevPost: '이전 글',
  publicNextPost: '다음 글',
  publicNoPost: '표시할 글이 없습니다.',
  publicPageOf: '/ {total} 페이지',
  publicReadMore: '더 보기',

  // ── 댓글: 공개 ──
  commentTitle: '댓글',
  commentCount: '{count}개의 댓글',
  commentEmptyState: '아직 작성된 댓글이 없습니다.',
  commentReplyButton: '답글',
  commentReplyCancel: '취소',
  commentMemberLabel: '회원',
  commentGuestLabel: '게스트',
  commentFormNameLabel: '이름',
  commentFormNamePlaceholder: '이름을 입력하세요',
  commentFormEmailLabel: '이메일 (선택, 공개되지 않음)',
  commentFormEmailPlaceholder: '이메일을 입력하세요',
  commentFormContentLabel: '댓글',
  commentFormContentPlaceholder: '댓글을 입력하세요',
  commentFormSubmitButton: '댓글 작성',
  commentFormSubmitReply: '답글 작성',
  commentFormSubmitting: '전송 중...',
  commentFormSuccess: '댓글이 등록되었습니다. 관리자 검토 후 표시됩니다.',
  commentFormError: '댓글 작성에 실패했습니다.',
  commentMaxLengthHint: '최대 2000자',
  commentLoginRequired: '댓글을 작성하려면 로그인이 필요합니다.',
  commentResetButton: '댓글 더 작성하기',
  commentDeletedLabel: '삭제된 댓글입니다.',

  // ── 태그 피커 ──
  tagPickerPlaceholder: '태그를 입력하거나 선택하세요',
  tagPickerLoading: '불러오는 중…',
  tagPickerInvalidName: '유효한 태그 이름이 아닙니다',
  tagPickerNoMatch: '일치하는 태그가 없습니다',
  tagPickerCreateNew: '새 태그 생성',

  // ── 태그 관리 ──
  tagAdminTitle: '태그 관리',
  tagAdminCreateButton: '+ 새 태그 추가',
  tagAdminNameLabel: '태그 이름',
  tagAdminSlugLabel: '태그 Slug',
  tagAdminDescriptionLabel: '태그 설명',
  tagAdminPostCount: '연결된 글',

  // ── 태그 클라우드 ──
  tagCloudTitle: '태그',
  tagCloudEmpty: '등록된 태그가 없습니다.',

  // ── 댓글 모더레이션 ──
  moderationTitle: '댓글 모더레이션',
  moderationAll: '전체',
  moderationPending: '대기',
  moderationApproved: '승인',
  moderationRejected: '거부',
  moderationSpam: '스팸',
  moderationApproveButton: '승인',
  moderationRejectButton: '거부',
  moderationSpamButton: '스팸',
  moderationDeleteButton: '삭제',
  moderationBulkApprove: '일괄 승인',
  moderationBulkReject: '일괄 거부',
  moderationBulkSpam: '스팸 처리',
  moderationBulkDelete: '일괄 삭제',
  moderationEmpty: '표시할 댓글이 없습니다.',
  moderationLoadError: '목록 조회 실패',
  moderationDeleteConfirm: '삭제하시겠습니까?',
  moderationBulkDeleteConfirm: '선택한 항목을 삭제하시겠습니까?',

  // ── 스케줄러 ──
  schedulerTitle: '예약 발행',
  schedulerPending: '예약 대기',
  schedulerProcessButton: '지금 처리',
  schedulerCancelButton: '예약 취소',
  schedulerEmpty: '예약된 글이 없습니다.',

  // ── 검색 ──
  searchTitle: '검색',
  searchPlaceholder: '검색어를 입력하세요',
  searchButton: '검색',
  searchNoResults: '검색 결과가 없습니다.',
  searchResultCount: '검색 결과 {count}건',

  // ── 유효성 검사 에러 메시지 ──
  validationTitleRequired: '제목을 입력해주세요',
  validationTitleMaxLength: '제목은 200자 이내로 입력해주세요',
  validationContentRequired: '본문을 입력해주세요',
  validationCategoryRequired: '카테고리를 선택해주세요',
  validationSlugRequired: 'Slug를 입력해주세요',
  validationSlugFormat: 'Slug는 소문자 영숫자와 하이픈만 사용할 수 있습니다',
  validationSlugMaxLength: 'Slug는 200자 이내로 입력해주세요',
  validationExcerptMaxLength: '요약은 500자 이내로 입력해주세요',
  validationUrlInvalid: '유효한 URL을 입력해주세요',
  validationUrlUnsafe: '안전하지 않은 URL 프로토콜입니다 (file:, javascript:, data: 사용 불가)',
  validationIdsRequired: '대상을 선택해주세요',
  validationTagNameRequired: '태그 이름을 입력해주세요',
  validationTagNameMaxLength: '태그 이름은 50자 이내로 입력해주세요',
  validationTagDescriptionMaxLength: '설명은 500자 이내로 입력해주세요',
  validationCommentContentRequired: '댓글 내용을 입력해주세요',
  validationCommentContentMaxLength: '댓글은 2000자 이내로 입력해주세요',
  validationCommentNameRequired: '이름을 입력해주세요',
  validationCommentNameMaxLength: '이름은 50자 이내로 입력해주세요',
  validationCommentEmailInvalid: '유효한 이메일을 입력해주세요',
  validationPostIdRequired: '포스트 ID가 필요합니다',

  // ── 공통 에러 ──
  errorUnknown: '알 수 없는 오류',
  errorNetwork: '네트워크 오류가 발생했습니다.',
  errorUnauthorized: '인증이 필요합니다.',
  errorForbidden: '접근 권한이 없습니다.',
  errorNotFound: '대상을 찾을 수 없습니다.',
  errorValidation: '입력 값이 유효하지 않습니다.',

  // ── 공통 UI ──
  commonConfirm: '확인',
  commonCancel: '취소',
  commonDelete: '삭제',
  commonEdit: '편집',
};
