/**
 * @withwiz/blog-core i18n 문자열 인터페이스
 *
 * 150+ 키로 관리자 UI, 공개 UI, 댓글, 태그, 모더레이션,
 * 유효성 검사 에러 메시지, 공통 문자열을 모두 커버한다.
 *
 * 호스트는 Partial<BlogI18nStrings>만 전달하면 나머지는 한국어 기본값으로 채워진다.
 */

export interface BlogI18nStrings {
  // ── 관리자 UI: 목록 / 공통 (20) ──
  adminListTitle: string;
  adminCreateButton: string;
  adminCreateTitle: string;
  adminEditTitle: string;
  adminSaveButton: string;
  adminCancelButton: string;
  adminPublishedLabel: string;
  adminUnpublishedLabel: string;
  adminFeaturedLabel: string;
  adminDeleteConfirm: string;
  adminBulkDeleteConfirm: string;
  adminListEmpty: string;
  adminUnknownError: string;
  adminPublishedSuffix: string;
  adminDraftSuffix: string;
  adminSearchPlaceholder: string;
  adminSelectAll: string;
  adminCategoryAll: string;
  adminCountSuffix: string;
  adminPerPageSuffix: string;
  adminAuthorLabel: string;
  adminBackButton: string;

  // ── 관리자 UI: 정렬 (3) ──
  adminSortCreatedAt: string;
  adminSortPublishedAt: string;
  adminSortUpdatedAt: string;

  // ── 관리자 UI: 뷰 / 탭 (6) ──
  adminViewEdit: string;
  adminViewPreviewDetail: string;
  adminViewPreviewList: string;
  adminTabList: string;
  adminTabEditPreview: string;
  adminTabDashboard: string;

  // ── 관리자 UI: 메타데이터 라벨 (4) ──
  adminMetaPublishedAt: string;
  adminMetaCreatedAt: string;
  adminMetaUpdatedAt: string;
  adminViewCountLabel: string;

  // ── 관리자 UI: 일괄 작업 (7) ──
  adminBulkPublish: string;
  adminBulkUnpublish: string;
  adminBulkFeature: string;
  adminBulkUnfeature: string;
  adminBulkDelete: string;
  adminBulkClear: string;
  adminBulkSelectedSuffix: string;

  // ── 관리자 폼: 라벨 & 플레이스홀더 (30) ──
  adminTitleLabel: string;
  adminTitlePlaceholder: string;
  adminTitleRequired: string;
  adminContentLabel: string;
  adminContentRequired: string;
  adminSlugLabel: string;
  adminSlugAutoGenerated: string;
  adminSlugDuplicate: string;
  adminSlugInvalid: string;
  adminSlugAvailable: string;
  adminSlugChecking: string;
  adminCategoryLabel: string;
  adminExcerptLabel: string;
  adminExcerptPlaceholder: string;
  adminCoverImageLabel: string;
  adminAttachmentsLabel: string;
  adminBlocksLabel: string;
  adminCtaLabel: string;
  adminPublishedAtLabel: string;
  adminBasicInfoLabel: string;
  adminRequiredLabel: string;
  adminOptionalLabel: string;
  adminFeaturedShort: string;
  adminItemNoTitle: string;
  adminSampleButton: string;
  adminBlocksHint: string;
  adminBlocksTag: string;
  adminImageRatioHint: string;
  adminContentPlaceholder: string;
  adminSlugPlaceholder: string;

  // ── 관리자 폼: 에디터 선택 (6) ──
  adminEditorTypeLabel: string;
  adminEditorTextarea: string;
  adminEditorRich: string;
  adminEditorBlock: string;
  adminEditorSwitchWarning: string;
  adminRichLinkPrompt: string;

  // ── 관리자 폼: 업로드 & 첨부 (12) ──
  adminUploadFailed: string;
  adminUnsupportedFileType: string;
  adminFileUploadError: string;
  adminImageOnlyAllowed: string;
  adminSaving: string;
  adminLoading: string;
  adminUploading: string;
  adminImageResizing: string;
  adminDropHere: string;
  adminImageUploadButton: string;
  adminAttachmentTitle: string;
  adminAttachmentAddButton: string;
  adminAttachmentMaxExceeded: string;
  adminAttachmentsHint: string;

  // ── 관리자 폼: CTA (6) ──
  adminCtaDescription: string;
  adminCtaToggle: string;
  adminCtaMessageLabel: string;
  adminCtaMessagePlaceholder: string;
  adminCtaButtonLabel: string;
  adminCtaButtonPlaceholder: string;
  adminCtaUrlLabel: string;

  // ── 관리자 대시보드 (8) ──
  dashboardTitle: string;
  dashboardTotal: string;
  dashboardPublished: string;
  dashboardUnpublished: string;
  dashboardFeatured: string;
  dashboardByCategory: string;
  dashboardRecentPosts: string;
  dashboardNoData: string;

  // ── 공개 UI (10) ──
  publicAllCategory: string;
  publicPrevPage: string;
  publicNextPage: string;
  publicBackToList: string;
  publicAttachmentsLabel: string;
  publicPrevPost: string;
  publicNextPost: string;
  publicNoPost: string;
  publicPageOf: string;
  publicReadMore: string;

  // ── 댓글: 공개 (14) ──
  commentTitle: string;
  commentCount: string;
  commentEmptyState: string;
  commentReplyButton: string;
  commentReplyCancel: string;
  commentMemberLabel: string;
  commentGuestLabel: string;
  commentFormNameLabel: string;
  commentFormNamePlaceholder: string;
  commentFormEmailLabel: string;
  commentFormEmailPlaceholder: string;
  commentFormContentLabel: string;
  commentFormContentPlaceholder: string;
  commentFormSubmitButton: string;
  commentFormSubmitReply: string;
  commentFormSubmitting: string;
  commentFormSuccess: string;
  commentFormError: string;
  commentMaxLengthHint: string;
  commentLoginRequired: string;
  commentResetButton: string;
  commentDeletedLabel: string;

  // ── 태그 피커 (5) ──
  tagPickerPlaceholder: string;
  tagPickerLoading: string;
  tagPickerInvalidName: string;
  tagPickerNoMatch: string;
  tagPickerCreateNew: string;

  // ── 태그 관리 (6) ──
  tagAdminTitle: string;
  tagAdminCreateButton: string;
  tagAdminNameLabel: string;
  tagAdminSlugLabel: string;
  tagAdminDescriptionLabel: string;
  tagAdminPostCount: string;

  // ── 태그 클라우드 (2) ──
  tagCloudTitle: string;
  tagCloudEmpty: string;

  // ── 댓글 모더레이션 (14) ──
  moderationTitle: string;
  moderationAll: string;
  moderationPending: string;
  moderationApproved: string;
  moderationRejected: string;
  moderationSpam: string;
  moderationApproveButton: string;
  moderationRejectButton: string;
  moderationSpamButton: string;
  moderationDeleteButton: string;
  moderationBulkApprove: string;
  moderationBulkReject: string;
  moderationBulkSpam: string;
  moderationBulkDelete: string;
  moderationEmpty: string;
  moderationLoadError: string;
  moderationDeleteConfirm: string;
  moderationBulkDeleteConfirm: string;

  // ── 스케줄러 (5) ──
  schedulerTitle: string;
  schedulerPending: string;
  schedulerProcessButton: string;
  schedulerCancelButton: string;
  schedulerEmpty: string;

  // ── 검색 (5) ──
  searchTitle: string;
  searchPlaceholder: string;
  searchButton: string;
  searchNoResults: string;
  searchResultCount: string;

  // ── 유효성 검사 에러 메시지 (20) ──
  validationTitleRequired: string;
  validationTitleMaxLength: string;
  validationContentRequired: string;
  validationCategoryRequired: string;
  validationSlugRequired: string;
  validationSlugFormat: string;
  validationSlugMaxLength: string;
  validationExcerptMaxLength: string;
  validationUrlInvalid: string;
  validationUrlUnsafe: string;
  validationIdsRequired: string;
  validationTagNameRequired: string;
  validationTagNameMaxLength: string;
  validationTagDescriptionMaxLength: string;
  validationCommentContentRequired: string;
  validationCommentContentMaxLength: string;
  validationCommentNameRequired: string;
  validationCommentNameMaxLength: string;
  validationCommentEmailInvalid: string;
  validationPostIdRequired: string;

  // ── 공통 에러 (6) ──
  errorUnknown: string;
  errorNetwork: string;
  errorUnauthorized: string;
  errorForbidden: string;
  errorNotFound: string;
  errorValidation: string;

  // ── 공통 UI (4) ──
  commonConfirm: string;
  commonCancel: string;
  commonDelete: string;
  commonEdit: string;
}
